server:
    port: 8080
    default-page-limit: 30
datasource:
    dsn: root:123456@tcp(10.0.3.151:3306)/gametools?charset=utf8mb4&parseTime=True&loc=Local
    auto-migrate: true
auth:
    token:
        expire-time: 30m
        signing-key: gametools
    excludes:
        - /api/login
datavcs:
    root-path: C:/Users/user/Desktop/dolt
